services:
  azn-rates:
    container_name: azn-rates
    build:
      context: .
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - .:/src
    env_file: .env
